name: Veracode IaC/Secrets Scanning

run-name: Veracode IaC/Secrets Scanning - ${{ github.event.client_payload.repository.name }}

on:
  repository_dispatch:
    types: [veracode-iac-secrets-scan]
    
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
    - uses: vincent-deng/veracode-github-app@aws-ecs-dynamodb
      with:
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        branch: ${{ github.event.client_payload.branch }}
        run_id: ${{ github.run_id }}
        repository_owner: ${{ github.event.client_payload.repository.owner }}
        repository_name: ${{ github.event.client_payload.repository.name }}
        event_type: ${{ github.event.client_payload.event_type }}
        enforce: true
       
  veracode-iac-secrets-scan:
    needs: [register]
    runs-on: ubuntu-latest
    name: Veracode IaC/Secrets Scanning

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}
          token: ${{ github.event.client_payload.token }}
      - name: Run Veracode IaC/Secrets Scanning
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
            vid: ${{ secrets.API_ID }}
            vkey: ${{ secrets.API_KEY }}
            command: "scan" 
            type: "directory"
            source: "./"
            format: "json"
            debug: false
            fail_build: true
